openapi: 3.0.0
info:
  title: Gotalk API
  description: A general API endpoint to handle comments even on static sites
  version: 0.0.1
servers:
  - url: /v1
paths:
  /ping:
    get:
      summary: Ping the server
      responses:
        '200':
          description: pong

  /user/new:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
              required:
                - name
                - email
      responses:
        '201':
          description: Registration complete
        '400':
          description: Bad request
        '409':
          description: Email already exists

  /users/{userid}/comments:
    post:
      summary: Post a comment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                threadid:
                  type: string
                content:
                  type: string
              required:
                - threadid
                - content
      parameters:
        - name: userid
          in: path
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Comment posted successfully
        '401':
          description: Unauthorized
        '400':
          description: Bad request

  /auth/comments/{commentid}:
    delete:
      summary: Delete a comment
      parameters:
        - name: commentid
          in: path
          required: true
          schema:
            type: string
        - name: threadid
          in: query
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Comment deleted successfully
        '404':
          description: Comment not found
        '401':
          description: Unauthorized
        '400':
          description: Bad request

  /admin/users/{userid}/sudo:
    post:
      summary: Grant admin privileges to a user
      parameters:
        - name: userid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Admin privileges granted
        '401':
          description: Unauthorized
        '404':
          description: User not found
        '500':
          description: Failed to grant admin privileges

  /admin/users/{userid}/sudo/revoke:
    post:
      summary: Revoke admin privileges from a user
      parameters:
        - name: userid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Admin privileges revoked
        '401':
          description: Unauthorized
        '404':
          description: User not found
        '500':
          description: Failed to revoke admin privileges

  /threads:
    get:
      summary: Retrieve all thread ids 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
      responses:
        '200':
          description: Threads retrieved successfully 
        '401':
          description: Unauthorized

  /threads/new:
    post:
      summary: Create a new thread
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
      responses:
        '201':
          description: Thread created successfully
        '401':
          description: Unauthorized

  /threads/{threadid}:
    delete:
      summary: Delete a thread
      parameters:
        - name: threadid
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Thread deleted successfully
        '400':
          description: Unable to parse request
        '401':
          description: Unauthorized
        '404':
          description: Thread not found

