openapi: 3.0.0
info:
  title: Gotalk API
  description: A general API endpoint to handle comments even on static sites
  version: 0.0.1
servers:
  - url: /v1
paths:
  /ping:
    get:
      summary: Ping the server
      responses:
        '200':
          description: pong

  /user/new:
    post:
      summary: Register a new user
      parameters:
        - name: name
          in: query
          required: true
          schema:
            type: string
        - name: email
          in: query
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Registration complete
        '400':
          description: <field> not set
        '409':
          description: <field> already exists

  /users/{userid}/comment:
    post:
      summary: Post a comment
      parameters:
        - name: userid
          in: path
          required: true
          schema:
            type: string
        - name: threadid
          in: query
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Comment posted successfully
        '401':
          description: Unauthorized
        '400':
          description: Bad request

  /auth/comments/{commentid}:
    delete:
      summary: Delete a comment
      parameters:
        - name: commentid
          in: path
          required: true
          schema:
            type: string
        - name: threadid
          in: query
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Comment deleted successfully
        '404':
          description: Comment not found
        '401':
          description: Unauthorized
        '400':
          description: Bad request
  
  /admin/users:
    get:
      summary: Get the list of users
      responses: 
        '200':
          description: Users retrieved successfully
        '401':
          description: Unauthorized

  /admin/users/{userid}/sudo:
    post:
      summary: Grant admin privileges to a user
      parameters:
        - name: userid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Admin privileges granted
        '401':
          description: Unauthorized
        '404':
          description: User not found
        '500':
          description: Failed to grant admin privileges

  /admin/users/{userid}/sudo/revoke:
    post:
      summary: Revoke admin privileges from a user
      parameters:
        - name: userid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Admin privileges revoked
        '401':
          description: Unauthorized
        '404':
          description: User not found
        '500':
          description: Failed to revoke admin privileges

  /admin/threads:
    get:
      summary: Retrieve all thread ids 
      responses:
        '200':
          description: Threads retrieved successfully 
        '401':
          description: Unauthorized

  /admin/threads/new:
    post:
      summary: Create a new thread
      parameters:
        - name: title
          in: query
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Thread created successfully
        '400':
          description: Thread title not set
        '409':
          description: Thread title already exists
        '401':
          description: Unauthorized

  /admin/threads/{threadid}:
    delete:
      summary: Delete a thread
      parameters:
        - name: threadid
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Thread deleted successfully
        '400':
          description: Unable to parse request
        '401':
          description: Unauthorized
        '404':
          description: Thread not found


